### ISSUE TITLE
[FEATURE_REQUEST] Watchdog messaging on DWS benchfail

### ISSUE THREAD

**Issue by 2ndtlmining** [RunOnFlux/fluxnode-multitool#106]
### Is your feature request related to a problem? If so, please describe.

Hey Team

Wanted to know if it would be possible to update the messaging that the Watchdog pushes when there is a DWS failure. The current messaging sometimes causes confusion to new users as they really think its a size issue but in fact its just a speed issue.
Below is current messaging:
![image](https://user-images.githubusercontent.com/108513481/213316206-e87c7941-4909-4fc5-9841-ae81f9ac7cf2.png)

### Describe the solution you'd like

What i was thinking is include the DWS score and remove the size messaging stating its lower. Very similar to the current wording. For example:

Current: Failed: HW requirements not sufficient for CUMULUS tier. CPU Cores: >=2 found 6 cores, Threads: >=4 found 6 threads, RAM: >=7 GB found 15 GB, EPS: >=240 found 496.2 eps, DownloadSpeed: >=25 Mb/s found 405.63 Mb/s, UploadSpeed: >=25 Mb/s found 379.025 Mb/s, StorageWithDiskWriteSpeedHigher180MBs: >=220 GB found 0 GB

Proposed: Failed: HW requirements not sufficient for CUMULUS tier. CPU Cores: >=2 found 6 cores, Threads: >=4 found 6 threads, RAM: >=7 GB found 15 GB, EPS: >=240 found 496.2 eps, DownloadSpeed: >=25 Mb/s found 405.63 Mb/s, UploadSpeed: >=25 Mb/s found 379.025 Mb/s, StorageWithDiskWriteSpeedHigher180MBs: >= 75.32 MBs

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by XK4MiLX** [comment]
Watchdog read error from benchmark so cant change that

**Comment by 2ndtlmining** [comment]
Thanks coming back so quick Kamil. No worries
