### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by lodotek** [RunOnFlux/fluxnode-multitool#123]
### Environment

Self-Hosted

### Version

latest master

### Describe the problem

I am trapped in the `Enter your discord user id` dialog
![image](https://user-images.githubusercontent.com/2421856/220502252-813b2e52-9605-43b8-b008-f47677100221.png)
No matter what I do (short of ctrl-c) I am stuck in this dialog, even if I click cancel.
The message is "▶ UserID is not valid try again.....................[✖]"

![image](https://user-images.githubusercontent.com/2421856/220502592-49b5c4b7-a97b-4f01-b4c7-98b744344ee7.png)

Please advise

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by JKTUNING** [comment]
Your Discord user ID is a number that is tied to your discord account. If you enter a letter OR skip then it will fail validation.

The easiest way to get your discord ID is to go into Discord settings -> App Settings -> Advanced and enable developer mode.

Then go back to Settings -> User Settings -> My Account then click the three … (dots) next to your username. Then click copy ID. Then enter that ID in the watchdog setup.

**Comment by lodotek** [comment]
> s

Thanks for the quick reply! How can I get back to the dialog to configure the Discord settings?

**Comment by JKTUNING** [comment]
You can run toolbox option 4 again to check/confirm the settings or you can view the config file here. 

`cat $HOME/watchdog/config.js`
