### ISSUE TITLE
./multitoolbox.sh: line 527: os-check: command not found[BUG] <title>

### ISSUE THREAD

**Issue by Miooiio** [RunOnFlux/fluxnode-multitool#130]
### Environment

Self-Hosted

### System

Ubuntu 22.04.2 LTS

### Version

22.04.2 LTS

### Describe the problem

Module: Install FluxNode
================================================================
./multitoolbox.sh: line 527: os-check: command not found

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by Miooiio** [comment]
Thanks to the guidance of friends from discord, solved by hanging http proxy

**Comment by TechDufus** [comment]
Glad to hear it! Thanks for the update.
