### ISSUE TITLE
[FEATURE_REQUEST] Use systemd when available

### ISSUE THREAD

**Issue by MorningLightMountain713** [RunOnFlux/fluxnode-multitool#144]
### Is your feature request related to a problem? If so, please describe.

Systemd is the canonical way to manage processes on capable OSes. It makes no sense to use pm2 when 99% of fluxnodes run a systemd capable OS.

Systemd can do everything pm2 can and then some.

Would be good to manage process startup ordering etc.

I'm happy to do the work to implement this...

### Describe the solution you'd like

Use systemd to manage flux ecosystem, fallback to pm2 where appropriate.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

Yes!

**Comment by XK4MiLX** [comment]
Systemd is great but pm2 is perfect for managing node.js  and due all working fine 
it is waste of time, better is improve other aspects of fluxos.

**Comment by XK4MiLX** [comment]
An improvement in this, what I see is to remove nodemon and replace it with a PM2 ecosystem file.

**Comment by MorningLightMountain713** [comment]
Fair enough, you got me on the "if it ain't broke, don't fix it" :)

I'll have a look at the nodemon stuff. Feel free to close this.
