### ISSUE TITLE
[BUG] Hardware benchmark

### ISSUE THREAD

**Issue by Oats-max** [RunOnFlux/fluxnode-multitool#151]
### Environment

Self-Hosted

### System

raspberry

### Version

v4.2.0

### Describe the problem

cd $HOME && ./lsblk -l -b -n /dev/${disc__array[i]} > /dev/null 2>&1

There will be no lsblk files in the home directory
Maybe it should be:

cd $HOME && lsblk -l -b -n /dev/${disc__array[i]} > /dev/null 2>&1

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.gg/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by XK4MiLX** [comment]
thx look i missed it.. when u install node that file is in $HOME
https://github.com/RunOnFlux/fluxnode-multitool/commit/721b2bd85bb54dbfa9d28e649832db3d8229ea9d
