### ISSUE TITLE
[BUG] More than 40 hours to dowload flux_explorer_bootstrap.tar.gz

### ISSUE THREAD

**Issue by PhoenixBS** [RunOnFlux/fluxnode-multitool#27]
### Environment

VPS

### System

Ubuntu 20.04 LTS

### Version

V7.2

### Describe the problem

Hello,

This morning at 9:00 am (Paris Hour) when I was building my new Cumulus node on my VPS , the time to download the boot strap file from cdn-12 was grather than 40 hours.
My VPS is hosted by Advin Servers and the ip is 204.10.194.177.
The VPS msut be located at Amsterdam (as showed here :  
![Advin Servers](https://user-images.githubusercontent.com/33147152/183441578-d7847e23-38a4-462b-8ba9-007106ab495a.jpg)
 
But traceroute says => Toronto (Canada) ( as showed bellow :
![AdvinTraceRoute](https://user-images.githubusercontent.com/33147152/183442414-d4704e9f-c137-449c-83be-a053f91f61c8.jpg)

To correct this problem, I had manually force the download on cdn-10. The download ended after 35 minutes.

The new Cumulus node had been correctly installed and is currently running without issue.

I hope these informations can help you.

Best Regards 

Eddie (TMFrance on Discord)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by matthewjdegarmo** [comment]
The following site shows me this IP lives in Laos, Asia and is owned by `Advin Services LLC`.
https://ip-api.com/#204.10.194.177

I recall you have a [submitted ticket](https://discord.com/channels/404415190835134464/925756014664503316/1006236588302422197) with Advin Services to get this looked at.

Unless they are able to get you an IP that does NOT trigger the Asia geo-location portion of the `multitoolbox` scripts, I would suggest that you run `multitoolbox option 6` and supply a different cdn bootstrap URL.

The format of the Bootstrap download files are as follows:
```bash
http://cdn-8.runonflux.io/apps/fluxshare/getfile/flux_explorer_bootstrap.tar.gz
```
The portion that you would replace is the `cdn-8` portion, where the number ranges between 5 and 12. I'm not exactly sure yet whish #'s belong to America vs Europe vs Asia, etc... BUT try a few and see which one works for you!

I've created issue #28 for this, to get some more clear documentation around which URLs belong to which geo-regions and so on.

I hope this is helpful and thank you for flying **Dufus Airlines**!

**Comment by matthewjdegarmo** [comment]
Okay, I see the discrepency...
This is the api call used in multitoolbox today:

---
```bash
curl -s -m 10 http://ip-api.com/json/204.10.194.177?fields=status,country,timezone
```
RESPONSE:
```json
{
  "status": "success",
  "country": "Laos",
  "timezone": "Asia/Vientiane"
}
```
---
And this is the api call that would give the correct info for this IP
```bash
curl -s -m 10 curl http://ipinfo.io/204.10.194.177/json
```
RESPONSE:
```json
{
  "ip": "204.10.194.177",
  "city": "Amsterdam",
  "region": "North Holland",
  "country": "NL",
  "loc": "52.3740,4.8897",
  "org": "AS206216 Advin Services LLC",
  "postal": "1012",
  "timezone": "Europe/Amsterdam",
  "readme": "https://ipinfo.io/missingauth"
}
```
---

We'll need to figure out if it's worth the switch to another ip geolocation provider or not.. stay tuned.

**Comment by AnushK-Fro** [comment]
Hey, I'm a representative of Advin Servers. We've went ahead and submitted the correct IP geolocation to IP-API (which may take up to 7 days to get processed). A lot of the IP geolocation services are generally inaccurate, especially with new IP ranges or providers, so IP-API is most likely showing old data of whoever used to previously operate the subnet/ASN. We've only been using our 204.10.194.0/24 subnet (and AS206216 ASN) for 5 months.

We've found IPInfo to be both the most accurate and the most up to date, so we would highly recommend them if you ever plan on switching to another IP Geolocation provider. Alternatively, you could provide the user with choice to choose which region the server is located in.

**Comment by matthewjdegarmo** [comment]
> Hey, I'm a representative of Advin Servers. We've went ahead and submitted the correct IP geolocation to IP-API (which may take up to 7 days to get processed). A lot of the IP geolocation services are generally inaccurate, especially with new IP ranges or providers, so IP-API is most likely showing old data of whoever used to previously operate the subnet/ASN. We've only been using our 204.10.194.0/24 subnet (and AS206216 ASN) for 5 months.
> 
> We've found IPInfo to be both the most accurate and the most up to date, so we would highly recommend them if you ever plan on switching to another IP Geolocation provider. Alternatively, you could provide the user with choice to choose which region the server is located in.

Thanks for the feedback!

@PhoenixBS Going forward, the bootstrap server url geolocation selection process will be completely based on download speed, **not** what your geolocation country is.

What I mean is, the `multitoolbox` script will do a quick speed-test against each of the CDN servers to see which one you download fastest from, and it will use the fastest one, regardless of if that server is in your country or not. 

Here's a quick screenshot of what this would look like in the `multitoolbox` install script.
![image](https://user-images.githubusercontent.com/46715299/188537592-88ea2f32-219d-412e-8581-1496aab388b3.png)
