### ISSUE TITLE
[FEATURE_REQUEST] Table to show what geo-server #'s go to which countries

### ISSUE THREAD

**Issue by TechDufus** [RunOnFlux/fluxnode-multitool#28]
### Is your feature request related to a problem? If so, please describe.

Not a problem, but when users want to provide the bootstrap URL instead of relying on the auto-detection implementation in the multitoolbox script.

### Describe the solution you'd like

It would be great to have a simple table documented for users to reference if a user us EU for example, and one of the EU servers is slow for them, they know other EU servers to try without having to guess. Something like this:

| Country | ID | 
| ------------- |:-------------:|
| Europe       | 5,6,7 |
| America      | 8,9,10 |
| Asia | 11,12   |

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by matthewjdegarmo** [comment]
Confirming the guess table above, the following #'s belong to the respective regions.

America: 4-7
Europe: 8-11
Asia: 12
