### ISSUE TITLE
[FEATURE_REQUEST] Provide KDA k: address within multitoolbox

### ISSUE THREAD

**Issue by d-derv** [RunOnFlux/fluxnode-multitool#29]
### Is your feature request related to a problem? If so, please describe.

An established node such as a Cumulus created two months ago did not have the option to provide the KDA k: address during setup. Currently the only way to provide the KDA address on an established node is through FluxOS and signing in with ZelID. This is a time consuming process if there are a large number of nodes to update.

### Describe the solution you'd like

Ask the user for their KDA k: address when using option 8 of multitoolbox.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by XK4MiLX** [comment]
added option 11 - FluxOS reconfiguration
