### ISSUE TITLE
[FEATURE_REQUEST] Beginner vs Advanced guided install prompts

### ISSUE THREAD

**Issue by GGoldie** [RunOnFlux/fluxnode-multitool#31]
### Is your feature request related to a problem? If so, please describe.

Currently there is not enough information given during the install for non-technical users to be able to locate required information (such as collateral Tx ID or output index) and therefore a guide is required for most

### Describe the solution you'd like

Create more prompts throughout the option 2 install that will guide the user through the install, such as where node info is located, the fact that their wallet private keys should NEVER be required, etc.

Also have the option for a power-user install, which skips all prompts and just asks for the needed info. This would be for experienced users who do not require help. Provide a prompt at the start to ask the user if they wish for a guided install, or not.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by TechDufus** [comment]
The more I've thought about this, the more I think this really falls under the realm of sufficient guides, and not the install script...

It would be very convoluted and complicated to provide different prompts and routes to get a node configured, when a guide would be perfect for this.

For this reason, I'm going to close this. Thank you for flying Dufus Airlines..
