### ISSUE TITLE
[FEATURE_REQUEST] Test bootstrap download speed during node Install

### ISSUE THREAD

**Issue by JKTUNING** [RunOnFlux/fluxnode-multitool#34]
### Is your feature request related to a problem? If so, please describe.

This feature request is to help speed up the bootstrap download process and to help with user's who are forced to use a server that has a less than optimal download speed.

For example, Asia only has 1 download server currently - server 12. Users have reported 40+ hr estimated download times for bootstrap files and with the current implementation of the code they are stuck using that server.

The only work around is to manually enter the URL with option 5 or in the install config file (option 6), but this requires the user to know the download URLs and best connection.

### Describe the solution you'd like

This feature would test the download speed of each server in the node installer's region and would pick the best one.

If the download speed isn't adequate within the user's region - then we would test the next region's servers to try and find the best speed.

Preliminary code seems to only add minimal time to the server selection process, with the potential to save the user a great deal of time if they are forced to use a sub optimal server due to their location.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

Yes!

**Comment by XK4MiLX** [comment]
initial speed test here
bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/cdn-speedtest.sh)
