### ISSUE TITLE
[BUG] Option 4 Parse error

### ISSUE THREAD

**Issue by GGoldie** [RunOnFlux/fluxnode-multitool#35]
### Environment

Self-Hosted

### System

Ubuntu 20.04

### Version

v7.2

### Describe the problem

When running option 4 in toolbox, I hit enter to all on screen prompts. Then at social pings, I select Discord and enter my discord webhook. I select not to receive @ pings, then give the node a name.

The script runs, and goes through fine. However, 2 errors appear:

- _parse error: Invalid numeric literal at line 1, column 10_
- (_23) Failed writing body_

These errors appear to have no affect on the node or watchdog installation

Screenshot attached below  

### Additional info

![unknown (1)](https://user-images.githubusercontent.com/96921031/184998100-556c238e-5254-4751-89dc-744a003f7b5a.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by XK4MiLX** [comment]
that error is relevant
