### ISSUE TITLE
[FEATURE_REQUEST] Need Username Environment check installed in MTB testnet as it is in mainnet

### ISSUE THREAD

**Issue by mattconres** [RunOnFlux/fluxnode-multitool#40]
### Is your feature request related to a problem? If so, please describe.

Please put the test function for the docker username into the testnet MTB as it is in Mainnet

### Describe the solution you'd like

Replace

usernew="$(whiptail --title "MULTITOOLBOX $dversion" --inputbox "Enter your username" 8 72 3>&1 1>&2 2>&3)"
usernew=$(awk '{print tolower($0)}' <<< "$usernew")
echo -e "${ARROW} ${CYAN}New User: ${GREEN}${usernew}${NC}"

With

if [[ -z "$usernew" ]]; then
  usernew="$(whiptail --title "MULTITOOLBOX $dversion" --inputbox "Enter your username" 8 72 3>&1 1>&2 2>&3)"
  usernew=$(awk '{print tolower($0)}' <<< "$usernew")
else
  echo -e "${PIN}${CYAN} Import docker user '$usernew' from environment variable............[${CHECK_MARK}${CYAN}]${NC}" && sleep 1
fi

echo -e "${ARROW} ${CYAN}New User: ${GREEN}${usernew}${NC}"

### Priority

High (The app does not function without it)

**Comment by TechDufus** [comment]
This was merged.
