### ISSUE TITLE
[FEEDBACK] Can not excute in China network

### ISSUE THREAD

**Issue by openxbmc** [RunOnFlux/fluxnode-multitool#45]
bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh) is blocked by China Firewall

**Comment by openxbmc** [comment]
Add more source?

**Comment by TheTrunk** [comment]
Hello, we have just updated the readme and you can use fastgit.org provider in this way
`bash -i <(curl -s https://raw.fastgit.org/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)`

**Comment by openxbmc** [comment]
Thanks man!
