### ISSUE TITLE
[FEATURE_REQUEST] Reinstall Flux Node Option 2 - Import UPNP Settings

### ISSUE THREAD

**Issue by Cabecinha84** [RunOnFlux/fluxnode-multitool#49]
### Is your feature request related to a problem? If so, please describe.

When reinstalling flux node option 2, the upnp settings are not imported what makes the need to execute the option 14 after the option 2 is finished.

### Describe the solution you'd like

Import UPNP settings when reinstalling a FluxNode under option 2. And execute what is needed to make it work like option 14.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by TechDufus** [comment]
I think this has been implemented already.

It was added in 3f39912c799faa1a14345660a31df211cca1629e

https://github.com/RunOnFlux/fluxnode-multitool/blob/122411adc103ca1cbacfd44b02a7e648fa6cdb27/install_pro.sh#L825-L827
