### ISSUE TITLE
[BUG] docker installation from script is not working

### ISSUE THREAD

**Issue by sygmak** [RunOnFlux/fluxnode-multitool#57]
### Environment

Self-Hosted

### System

Ubuntu 20.04

### Describe the problem

during run the script from:
bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)

 and choose 1, installation is going well until the result :
![image](https://user-images.githubusercontent.com/67188142/193766261-8942a237-4903-44d4-93df-f24ed7a9136a.png)

than trying to install flux node but:
![image](https://user-images.githubusercontent.com/67188142/193766822-0a20a377-7513-492c-8196-1d2e9de1e823.png)

please help.

installation was tryied on Ubuntu 20.04 from windows 10 store (which probably is WSL)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by matthewjdegarmo** [comment]
Docker in WSL will not work without the `Docker Desktop CE` installed in Windows..

WSL isn't able to run the docker daemon, but needs to connect to the daemon running in Windows..

I bet if you installed `Docker Desktop CE` in Windows, that this **might** work... but if not, you will need to virtualize your node with Hyper-V, VirtualBox, etc...

**Comment by matthewjdegarmo** [comment]
I'm going to close this, just because I know that this is the issue.

If you have issues with a virtualized node, feel free to hit up the #communiny-support Discord channel.
