### ISSUE TITLE
🚨 ERROR: OS version not supported everytime i try to run toolbox opt 1&2

### ISSUE THREAD

**Issue by gonzo4233** [RunOnFlux/fluxnode-multitool#71]
### Environment

Self-Hosted

### System

ubunto 20.4

### Version

v7.4

### Describe the problem

I have tried installing every version of ubunto, and no matter what I do, I get the same error message, I cannot get docker or flux node to install?? need help, been trying for 3 weeks solid 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by TechDufus** [comment]
I see this is closed... Was this resolved?

**Comment by chrisbagsrocks** [comment]
I am having the same issue as well

**Comment by TechDufus** [comment]
> I am having the same issue as well

Can you please confirm the version of Ubuntu you have installed?

**Comment by chrisbagsrocks** [comment]
I figured out the issue. I was installing 20.04, and it asked in the beginning if I wanted to install updates. I selected "no" and proceeded installing. Once the installation was complete it proceeded to install the updates anyway.  

Solution: Cancel Update & Reboot

**Comment by TechDufus** [comment]
@chrisbagsrocks Thanks for the fast response!
