### ISSUE TITLE
[BUG] Multi nodes - Incorrect flux front end URL

### ISSUE THREAD

**Issue by floriangrousset** [RunOnFlux/fluxnode-multitool#77]
### Environment

Self-Hosted

### System

Ubuntu 20.04 LTS

### Version

Latest from GitHub

### Describe the problem

**Background:**
I'm installing multiple nodes using the 8 available TCP ports. For that I've prepared the install_config.json files for each node and run the installation for them.

**Installation process:**
1. Switch to root user
2. Run the multitool script and install Docker with option 1
3. Switch to the local user
4. Copy install_config.json containing all the config
5. Run the multitool script and install Flux with option 2
6. Installation goes all well and services are up and running at the end

BUT: there is an incorrect information outputted on the terminal.

Before the "FLUXNODE INSTALLATION COMPLETED" ascii art banner, it's outputting this:
`📌 To access your FluxOS use this url: http://192.168.100.8:16196`
(note the 16196 port which is the correct one for that 8th node)

But then, at the very end of the installation, before the system returns to the shell prompt, it's outputting this:
`📌 To access your frontend to Flux enter this in as your url: 70.114.12.58:16126`
(note that this is the default 16126 port, which is incorrect and should be the user specified port 16196 for this node)

This is a pretty minor bug but can mislead users.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by JKTUNING** [comment]
Added to PR #76 to update the ZELFRONTPORT variable so it displays the correct port.

**Comment by TechDufus** [comment]
Closed by bd9a09c36eeb7668c99c8b07e1641dcbc0472d8b
