### ISSUE TITLE
[BUG] Option 13 Mongodb hard fix doesn't always fix mongodb

### ISSUE THREAD

**Issue by Cabecinha84** [RunOnFlux/fluxnode-multitool#82]
### Environment

Self-Hosted

### Describe the problem

Some type of corrupted mongodb the hard fix option on multitool is not working properly. After applied we still get a connection refused error when fluxOs tries to connect to mongodb.

Please use this simple uninstall instead

sudo apt-get remove ^mongodb --purge -y

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by XK4MiLX** [comment]
purge command updated
