### ISSUE TITLE
[FEATURE_REQUEST] Include Option for MultiNode Setup during initial install

### ISSUE THREAD

**Issue by Meatball13** [RunOnFlux/fluxnode-multitool#92]
### Is your feature request related to a problem? If so, please describe.

Somewhat, yes.  Currently, if you have multiple nodes setup at an IP address, during the initial install of a new node, it is built out using the default IP address and port (16126).  I have had this cause issues as I already have a node running on that port and have at times had to shut down _all_ my nodes, restart my router, and then restart the nodes one at a time after the new node has been configured tp enable UPnP / Port setting using the multitool option 14.

### Describe the solution you'd like

As part of the initial install, before the node tries to 'get on the network' ask if it is part of a multinode setup and allow selection of UPnP and port number similar to what happens when option 14 is run with the multitool.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by JKTUNING** [comment]
If you are setting up a node with upnp then you can run option 6 before you run option 2.

Option 6 sets up an install conf file which will ask if you want to enable upnp and will automatically set it up for you when you run option 2.

Plus, it saves the conf file so if you ever need to reinstall for any reason you can do that without imputing any data.

**Comment by TechDufus** [comment]
@Meatball13 I believe what you're asking for may be resolved with 7d93bd4 which is currently in our DEV branch.
