### ISSUE TITLE
Is there a fluxnode-multitool that will work with newer ubuntu files greater then 20.04

### ISSUE THREAD

**Issue by mlyons201** [RunOnFlux/fluxnode-multitool#97]
### Question

Found many problems with 20.04 version on my Pi, the newer ubuntu program works great but multitool will not work with that version

### Category

Option 1

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of multitoolbox
- [X] You've checked that this [issue hasn't already been raised](https://github.com/RunOnFlux/fluxnode-multitool/issues?q=is%3Aissue)
- [X] You've checked the official [RunOnFlux Discord](https://discord.io/runonflux) Pinned messages and FAQ ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/RunOnFlux/fluxnode-multitool/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by JKTUNING** [comment]
Flux OS depends on MongoDB. MongoDB does not officially support Ubuntu 22.04 or 22.10.

That is why the installer does not allow you to use those versions.

What issues are you having with Ubuntu 20.04? There are many users running it on a Pi with a Flux node.

**Comment by mlyons201** [comment]
My problems are with the Ubuntu 20.04, the pi fails to connect to wifi either wireless or with Ethernet cable. I tried numerous times rewriting to ssd and no go.  My next try is to connect pi to terminal and see what is going on but I need a hdmi micro cable to do it

**Comment by pilchor** [comment]
Hello,
Is there a way to manual install flux node on 22.04 arm ? (server already on 22.04 with lot of stuuf on it)
